FROM nginx:latest

COPY nginx.conf /etc/nginx/nginx.conf
COPY generate_cert.sh /etc/nginx/ssl/generate_cert.sh
COPY reverse_proxy.conf /etc/nginx/conf.d/reverse_proxy.conf

RUN apt-get update && apt-get install -y net-tools && \
    chmod +x /etc/nginx/ssl/generate_cert.sh && \
    /etc/nginx/ssl/generate_cert.sh
